
utils::globalVariables(c('person_id', 'patid', 'start_date', 'end_date', 'fu',
                         'anomaly_yn', 'cl', 'event_a_name', 'event_b_name', 'event_a_num',
                         'event_b_num', 'event_count', 'event_name', 'event_type',
                         'eventa_mean', 'eventb_mean', 'facet_col', 'filt_col',
                         'lcl', 'mean_allsiteprop', 'denom', 'dist_eucl_mean',
                         'dist_mean', 'dist_mean_sum', 'event_a_index_date',
                         'event_b_occurrence_date', 'event_date', 'event_n',
                         'label', 'lb', 'mad_val', 'median_prop', 'n_pts_thrs',
                         'name', 'num_days', 'prop_miss', 'prop_pts_thrs',
                         'pts_without_both', 'sd_val', 'with_both', 'nums',
                         'mean_site_loess', 'mean_val', 'median_val', 'n_grp',
                         'overall_sd', 'prop_col', 'prop_event', 'pt_ct', 'site',
                         'site_loess', 'text_raw', 'text_smooth', 'user_cutoff',
                         'time_end', 'time_increment', 'time_start', 'tooltip',
                         'total_pts', 'ucl', 'value', 'x', 'y', 'ycol', 'zscr',
                         'closest_site', 'delim', 'farthest_site', 'iqr_val', 'med',
                         'nvar', 'q1', 'q3', 'site_anoms', 'site_w_anom'))
