
#' Patient Event Sequencing -- Output Generation
#'
#' Using the tabular output generated by `pes_process`, this function will build a graph to
#' visualize the results. Each function configuration will output a bespoke ggplot. Theming can
#' be adjusted by the user after the graph has been output using `+ theme()`. Most graphs can
#' also be made interactive using `make_interactive_squba()`
#'
#' @param process_output *tabular input* || **required**
#'
#'   The tabular output produced by `pes_process`
#'
#'   Note any patient-level results generated are not intended to be used with this function.
#'
#' @param large_n *boolean* || defaults to `FALSE`
#'
#'   For Multi-Site analyses, a boolean indicating whether the large N
#'   visualization, intended for a high volume of sites, should be used. This
#'   visualization will produce high level summaries across all sites, with an
#'   option to add specific site comparators via the `large_n_sites` parameter.
#'
#' @param large_n_sites *vector* || defaults to `NULL`
#'
#'   When `large_n = TRUE`, a vector of site names that can add site-level information
#'   to the plot for comparison across the high level summary information.
#'
#' @return This function will produce a graph to visualize the results
#'         from `pes_process` based on the parameters provided. The default
#'         output is typically a static ggplot or gt object, but interactive
#'         elements can be activated by passing the plot through `make_interactive_squba`.
#'         For a more detailed description of output specific to each check type,
#'         see the PEDSpace metadata repository
#'
#' @example inst/example-pes_process_output.R
#'
#' @export
#'
pes_output <- function(process_output,
                       large_n = FALSE,
                       large_n_sites = NULL){

  # extract output function
  output_function <- process_output %>% collect() %>% ungroup() %>% distinct(output_function) %>% pull()


  if(output_function == 'pes_ss_exp_cs'){

    pes_output <- pes_ss_exp_cs(process_output = process_output)

  }else if(output_function == 'pes_ss_anom_cs'){

    cli_alert_danger('There is no available Single Site, Anomaly Detection, Cross-Sectional
                     output for this module. Please choose another output function.')

  }else if(output_function == 'pes_ms_exp_cs'){

    pes_output <- pes_ms_exp_cs(process_output = process_output,
                                large_n = large_n,
                                large_n_sites = large_n_sites)

  }else if(output_function == 'pes_ms_anom_cs'){

    pes_output <- pes_ms_anom_cs(process_output = process_output,
                                 large_n = large_n,
                                 large_n_sites = large_n_sites)

  }else if(output_function == 'pes_ss_exp_la'){

    pes_output <- pes_ss_exp_la(process_output = process_output)

  }else if(output_function == 'pes_ss_anom_la'){

    pes_output <- pes_ss_anom_la(process_output = process_output)

  }else if(output_function == 'pes_ms_exp_la'){

    pes_output <- pes_ms_exp_la(process_output = process_output,
                                large_n = large_n,
                                large_n_sites = large_n_sites)

  }else if(output_function == 'pes_ms_anom_la'){

    pes_output <- pes_ms_anom_la(process_output = process_output,
                                 large_n = large_n,
                                 large_n_sites = large_n_sites)

  }else{cli::cli_abort('Please enter a valid output_function for this check type.')}

  return(pes_output)
}
