
#'
#' @import ggplot2
#' @import ggiraph
#' @import gt
#' @importFrom qicharts2 qic
#' @importFrom tidyr uncount
#' @importFrom tidyr pivot_longer
#' @importFrom stats median
#' @importFrom patchwork wrap_plots
#' @importFrom patchwork plot_layout
#' @importFrom graphics text
NULL

#' *Single Site, Exploratory, Cross-Sectional*
#'
#' @param process_output output generated by the `pes_process` function
#'
#' @return a patchworked object with a histogram showing the distribution of days between events
#'         with a line representing the median number of days and a bar graph representing the
#'         proportion of patients excluded from the histogram because they did not have evidence
#'         of event b
#' @return a bar graph representing the proportion of patients that meet a set of
#'         thresholds: 30 days, 60 days, 90 days, one year, and the user provided
#'         threshold value
#'
pes_ss_exp_cs <- function(process_output){


  expand_cts <- process_output %>%
    uncount(pt_ct)

  median_days <- median(expand_cts$num_days, na.rm = TRUE)

  hstgrm <- ggplot(expand_cts, aes(x = num_days, fill = num_days, group = num_days)) +
    geom_histogram() +
    geom_vline(xintercept = median_days,
               linetype = 'dotted') +
    theme_minimal() +
    theme(legend.position = 'none') +
    scale_fill_squba(discrete = FALSE) +
    labs(x = 'Days Between Events',
         title = 'Distribution of Time Between Events')

  ## Missing Event Bar Graph
  missing_events <- process_output %>%
    mutate(prop_miss = pts_without_both / total_pts,
           xlab = '') %>%
    distinct(prop_miss, xlab)

  miss_grph <- missing_events %>%
    ggplot(aes(y = prop_miss, x = xlab, fill = xlab)) +
    geom_col(show.legend = FALSE) +
    geom_label(aes(label = round(prop_miss, 3)), fill = 'white') +
    scale_fill_manual(values = squba_colors_standard[[2]]) +
    theme_minimal() +
    ylim(0,1) +
    labs(x = '',
         y = 'Proportion Patients without Both Events')

  thrs_cutoffs <- expand_cts %>%
    mutate(user_thrs = ifelse(abs(num_days) <= user_cutoff, 1, 0),
           thirty_thrs = ifelse(abs(num_days) <= 30, 1, 0),
           sixty_thrs = ifelse(abs(num_days) <= 60, 1, 0),
           ninety_thrs = ifelse(abs(num_days) <= 90, 1, 0),
           year_thrs = ifelse(abs(num_days) <= 365, 1, 0)) %>%
    pivot_longer(cols = c('user_thrs', 'thirty_thrs', 'sixty_thrs',
                          'ninety_thrs', 'year_thrs')) %>%
    group_by(site, user_cutoff, total_pts, name) %>%
    summarise(n_pts_thrs = sum(value, na.rm = TRUE)) %>%
    mutate(prop_pts_thrs = round(n_pts_thrs / total_pts, 3))

  bgrph <- thrs_cutoffs %>%
    mutate(label = case_when(name == 'thirty_thrs' ~ '30 days',
                             name == 'sixty_thrs' ~ '60 days',
                             name == 'ninety_thrs' ~ '90 days',
                             name == 'year_thrs' ~ '1 year',
                             name == 'user_thrs' ~ paste0('User Threshold \n',
                                                          user_cutoff, ' days')),
           nums = case_when(name == 'thirty_thrs' ~ 1,
                            name == 'sixty_thrs' ~ 2,
                            name == 'ninety_thrs' ~ 3,
                            name == 'year_thrs' ~ 4,
                            name == 'user_thrs' ~ 5)) %>%
    arrange(nums) %>%
    mutate(lb = factor(label, levels = unique(label))) %>%
    ggplot(aes(x = lb, y = prop_pts_thrs, fill = lb)) +
    geom_col() +
    theme_minimal() +
    theme(legend.position = 'none') +
    scale_fill_squba() +
    labs(x = 'Threshold',
         y = 'Proportion Patients',
         title = 'Proportion of Patients where Events \nOccur within Threshold Window')

  bgrph[["metadata"]] <- tibble('pkg_backend' = 'plotly',
                                'tooltip' = FALSE)

  plt_grp <- patchwork::wrap_plots(hstgrm, miss_grph) +
    patchwork::plot_layout(widths = c(8, 3))

  otpt <- list(plt_grp,
               bgrph)

  return(otpt)

}


#' *Multi-Site, Exploratory, Cross-Sectional*
#'
#' @param process_output output generated by the `pes_process` function
#' @param large_n a boolean indicating whether the large N visualization, intended for a high
#'                volume of sites, should be used; defaults to FALSE
#' @param large_n_sites a vector of site names that can optionally generate a filtered visualization
#'
#' @return a bar graph representing the proportion of patients at each site
#'         that meet a set of thresholds: 30 days, 60 days, 90 days, one year,
#'         and the user provided threshold value
#'
#'         dotted line represents the all site median
#'
pes_ms_exp_cs <- function(process_output,
                          large_n = FALSE,
                          large_n_sites = NULL){


  expand_cts <- process_output %>%
    uncount(pt_ct)

  without_both_thrs <- process_output %>%
    select(site, user_cutoff, total_pts, pts_without_both) %>%
    pivot_longer(cols = 'pts_without_both',
                 names_to = 'name',
                 values_to = 'n_pts_thrs') %>%
    mutate(prop_pts_thrs = round(n_pts_thrs / total_pts, 3)) %>% distinct()

  thrs_cutoffs <- expand_cts %>%
    mutate(user_thrs = ifelse(abs(num_days) <= user_cutoff, 1, 0),
           thirty_thrs = ifelse(abs(num_days) <= 30, 1, 0),
           sixty_thrs = ifelse(abs(num_days) <= 60, 1, 0),
           ninety_thrs = ifelse(abs(num_days) <= 90, 1, 0),
           year_thrs = ifelse(abs(num_days) <= 365, 1, 0)) %>%
    pivot_longer(cols = c('user_thrs', 'thirty_thrs', 'sixty_thrs',
                          'ninety_thrs', 'year_thrs')) %>%
    group_by(site, user_cutoff, total_pts, name) %>%
    summarise(n_pts_thrs = sum(value, na.rm = TRUE)) %>%
    mutate(prop_pts_thrs = round(n_pts_thrs / total_pts, 3)) %>%
    union(without_both_thrs) %>%
    group_by(name) %>%
    mutate(median_prop = median(prop_pts_thrs))

  if(!large_n || large_n && !is.null(large_n_sites)){

    if(large_n && !is.null(large_n_sites)){
      thrs_cutoffs <- thrs_cutoffs %>%
        filter(site %in% large_n_sites)
    }

    bgrph <- thrs_cutoffs %>%
      mutate(label = case_when(name == 'thirty_thrs' ~ '30 days',
                               name == 'sixty_thrs' ~ '60 days',
                               name == 'ninety_thrs' ~ '90 days',
                               name == 'year_thrs' ~ '1 year',
                               name == 'user_thrs' ~ paste0('User Threshold \n',
                                                            user_cutoff, ' days'),
                               name == 'pts_without_both' ~ 'Both Events \nNot Present'),
             nums = case_when(name == 'thirty_thrs' ~ 1,
                              name == 'sixty_thrs' ~ 2,
                              name == 'ninety_thrs' ~ 3,
                              name == 'year_thrs' ~ 4,
                              name == 'user_thrs' ~ 5,
                              name == 'pts_without_both' ~ 6)) %>%
      arrange(nums) %>%
      # mutate(lb = factor(label, levels = unique(label))) %>%
      ggplot(aes(y = site, x = prop_pts_thrs, fill = label)) +
      geom_col() +
      facet_wrap(~factor(nums, labels = unique(label))) +
      geom_vline(mapping = aes(xintercept = median_prop),
                 linetype = 'dotted') +
      theme_minimal() +
      theme(legend.position = 'none') +
      scale_fill_squba() +
      labs(x = 'Site',
           y = 'Proportion Patients',
           title = 'Proportion of Patients where Events \nOccur within Threshold Window')
  }else{

    allsite_pts <- process_output %>%
      distinct(site, total_pts, pts_without_both) %>%
      summarise(total_pts = sum(total_pts),
                pts_without_both = sum(pts_without_both)) %>%
      mutate(site = 'all sites')

    allsite_wo <- process_output %>%
      select(-c(total_pts, pts_without_both)) %>%
      mutate(site = 'all sites') %>%
      left_join(allsite_pts) %>%
      select(site, user_cutoff, total_pts, pts_without_both) %>%
      pivot_longer(cols = 'pts_without_both',
                   names_to = 'name',
                   values_to = 'n_pts_thrs') %>%
      mutate(prop_pts_thrs = round(n_pts_thrs / total_pts, 3)) %>% distinct()

    allsite_summs <- thrs_cutoffs %>%
      mutate(q1 = stats::quantile(prop_pts_thrs, 0.25),
             q3 = stats::quantile(prop_pts_thrs, 0.75)) %>%
      distinct(median_prop, q1, q3, name) %>% mutate(site = 'all sites')

    allsite_props <- expand_cts %>%
      select(-c(total_pts, pts_without_both)) %>%
      mutate(site = 'all sites') %>%
      left_join(allsite_pts) %>%
      mutate(user_thrs = ifelse(abs(num_days) <= user_cutoff, 1, 0),
             thirty_thrs = ifelse(abs(num_days) <= 30, 1, 0),
             sixty_thrs = ifelse(abs(num_days) <= 60, 1, 0),
             ninety_thrs = ifelse(abs(num_days) <= 90, 1, 0),
             year_thrs = ifelse(abs(num_days) <= 365, 1, 0)) %>%
      pivot_longer(cols = c('user_thrs', 'thirty_thrs', 'sixty_thrs',
                            'ninety_thrs', 'year_thrs')) %>%
      group_by(site, user_cutoff, total_pts, name) %>%
      summarise(n_pts_thrs = sum(value, na.rm = TRUE)) %>%
      mutate(prop_pts_thrs = round(n_pts_thrs / total_pts, 3)) %>%
      union(allsite_wo) %>%
      left_join(allsite_summs)

    bgrph <- allsite_props %>%
      mutate(label = case_when(name == 'thirty_thrs' ~ '30 days',
                               name == 'sixty_thrs' ~ '60 days',
                               name == 'ninety_thrs' ~ '90 days',
                               name == 'year_thrs' ~ '1 year',
                               name == 'user_thrs' ~ paste0('User Threshold \n',
                                                            user_cutoff, ' days'),
                               name == 'pts_without_both' ~ 'Both Events \nNot Present'),
             nums = case_when(name == 'thirty_thrs' ~ 1,
                              name == 'sixty_thrs' ~ 2,
                              name == 'ninety_thrs' ~ 3,
                              name == 'year_thrs' ~ 4,
                              name == 'user_thrs' ~ 5,
                              name == 'pts_without_both' ~ 6)) %>%
      arrange(nums) %>%
      ggplot(aes(y = site, x = prop_pts_thrs, fill = label)) +
      geom_col() +
      geom_errorbar(aes(y=site, x=prop_pts_thrs, xmin=q1, xmax=q3)) +
      geom_point(aes(y = site, x = median_prop)) +
      facet_wrap(~factor(nums, labels = unique(label))) +
      # geom_vline(mapping = aes(xintercept = median_prop),
      #            linetype = 'dotted') +
      theme_minimal() +
      theme(legend.position = 'none') +
      scale_fill_squba() +
      labs(x = 'Site',
           y = 'Proportion Patients',
           title = 'Proportion of Patients where Events \nOccur within Threshold Window')

  }

  bgrph[["metadata"]] <- tibble('pkg_backend' = 'plotly',
                                'tooltip' = FALSE)

  return(bgrph)

}

#' *Single Site, Exploratory, Longitudinal*
#'
#' @param process_output output generated by the `pes_process` function
#'
#' @return a line graph displaying the proportion of patients meeting the user provided
#'         threshold of time between events over time
#'
pes_ss_exp_la <- function(process_output){

  expand_cts <- process_output %>%
    uncount(pt_ct)

  time_period <- process_output %>% select(time_increment) %>% distinct() %>% pull()
  thrs <- process_output %>% select(user_cutoff) %>% distinct() %>% pull()

  thrs_cutoffs <- expand_cts %>%
    mutate(user_thrs = ifelse(abs(num_days) <= user_cutoff, 1, 0),
           thirty_thrs = ifelse(abs(num_days) <= 30, 1, 0),
           sixty_thrs = ifelse(abs(num_days) <= 60, 1, 0),
           ninety_thrs = ifelse(abs(num_days) <= 90, 1, 0),
           year_thrs = ifelse(abs(num_days) <= 365, 1, 0),
           pts_without_both = ifelse(is.na(num_days), 1, 0)) %>%
    pivot_longer(cols = c('user_thrs', 'thirty_thrs', 'sixty_thrs',
                          'ninety_thrs', 'year_thrs', 'pts_without_both')) %>%
    group_by(site, user_cutoff, total_pts, name, time_start) %>%
    summarise(n_pts_thrs = sum(value, na.rm = TRUE)) %>%
    mutate(prop_pts_thrs = round(n_pts_thrs / total_pts, 3),
           text = paste0('Proportion: ', prop_pts_thrs,
                         '\nTotal Patients: ', total_pts,
                         '\nSite: ', site)) %>% ungroup() %>%
    mutate(label = case_when(name == 'thirty_thrs' ~ '30 days',
                             name == 'sixty_thrs' ~ '60 days',
                             name == 'ninety_thrs' ~ '90 days',
                             name == 'year_thrs' ~ '1 year',
                             name == 'user_thrs' ~ paste0('User Threshold \n',
                                                          user_cutoff, ' days'),
                             name == 'pts_without_both' ~ 'Both Events \nNot Present'),
           nums = case_when(name == 'thirty_thrs' ~ 1,
                            name == 'sixty_thrs' ~ 2,
                            name == 'ninety_thrs' ~ 3,
                            name == 'year_thrs' ~ 4,
                            name == 'user_thrs' ~ 5,
                            name == 'pts_without_both' ~ 6))


  lgrph <- ggplot(thrs_cutoffs %>% arrange(nums),
                 aes(x = time_start, y = prop_pts_thrs, color = label, group = label, text = text)) +
    geom_line() +
    theme_minimal() +
    scale_color_squba() +
    labs(y = 'Proportion',
         x = 'Time',
         color = 'Threshold Cutoff',
         title = paste0('Proportion of Patients Meeting Each Threshold'),
         subtitle = paste0('When Event A occurs within each ', time_period))

  lgrph[["metadata"]] <- tibble('pkg_backend' = 'plotly',
                                'tooltip' = TRUE)

  return(lgrph)

}

#' *Multi-Site, Exploratory, Longitudinal*
#'
#' @param process_output output generated by the `pes_process` function
#' @param large_n a boolean indicating whether the large N visualization, intended for a high
#'                volume of sites, should be used; defaults to FALSE
#' @param large_n_sites a vector of site names that can optionally generate a filtered visualization
#'
#' @return a line graph displaying the proportion of patients meeting the user provided
#'         threshold of time between events over time; each line represents an individual site,
#'         with an additional line representing the all site median
#'
pes_ms_exp_la <- function(process_output,
                          large_n = FALSE,
                          large_n_sites = NULL){

  expand_cts <- process_output %>%
    uncount(pt_ct)

  time_period <- process_output %>% select(time_increment) %>% distinct() %>% pull()
  thrs <- process_output %>% select(user_cutoff) %>% distinct() %>% pull()

  thrs_cutoffs <- expand_cts %>%
    mutate(user_thrs = ifelse(abs(num_days) <= user_cutoff, 1, 0)) %>%
    pivot_longer(cols = c('user_thrs')) %>%
    group_by(site, user_cutoff, total_pts, name, time_start) %>%
    summarise(n_pts_thrs = sum(value, na.rm = TRUE)) %>%
    mutate(prop_pts_thrs = round(n_pts_thrs / total_pts, 3),
           text = paste0('Proportion: ', prop_pts_thrs,
                         '\nTotal Patients: ', total_pts)) %>% ungroup()

  allsite_median <- thrs_cutoffs %>%
    group_by(name, time_start) %>%
    summarise(med = stats::median(prop_pts_thrs),
              q1 = stats::quantile(prop_pts_thrs, 0.25),
              q3 = stats::quantile(prop_pts_thrs, 0.75)) %>%
    pivot_longer(cols = c(med, q1, q3),
                 values_to = 'prop_pts_thrs',
                 names_to = 'stt') %>%
    mutate(site = case_when(stt == 'med' ~ 'All Site Median',
                            stt == 'q1' ~ 'All Site Q1',
                            stt == 'q3' ~ 'All Site Q3'),
           text = paste0(site, ': ', prop_pts_thrs)) %>%
    ungroup() %>%
    select(site, time_start, prop_pts_thrs, text) %>% distinct()


  if(!large_n || large_n && !is.null(large_n_sites)){

    if(large_n && !is.null(large_n_sites)){
      thrs_cutoffs <- thrs_cutoffs %>% filter(site %in% large_n_sites)
    }

    grph <- ggplot(thrs_cutoffs,
                   aes(x = time_start, y = prop_pts_thrs, color = site)) +
      geom_line() +
      geom_line(data = filter(allsite_median, site == "All Site Median"), size = 1.5) +
      theme_minimal() +
      scale_color_squba() +
      labs(y = 'Proportion',
           x = 'Time',
           color = 'Site',
           title = paste0('Proportion of Patients Meeting \n', thrs, ' Day User Threshold'),
           subtitle = paste0('When Event A occurs within each ', time_period))

  }else{
    grph <- ggplot(allsite_median,
                   aes(x = time_start, y = prop_pts_thrs, color = site)) +
      geom_line() +
      # geom_line(data = filter(allsite_median, site == "All Site Median"), size = 1.5) +
      theme_minimal() +
      scale_color_squba() +
      labs(y = 'Proportion',
           x = 'Time',
           color = 'Site',
           title = paste0('Proportion of Patients Meeting \n', thrs, ' Day User Threshold'),
           subtitle = paste0('When Event A occurs within each ', time_period))
  }

  grph[["metadata"]] <- tibble('pkg_backend' = 'plotly',
                               'tooltip' = FALSE)

  return(grph)

}


#' *Single Site, Anomaly, Longitudinal*
#'
#' @param process_output output generated by the `pes_process` function
#'
#' @return a control chart highlighting anomalies in the proportion of patients
#'         meeting the user defined threshold of time between events
#'
pes_ss_anom_la <- function(process_output){

  thrs <- process_output %>% distinct(user_cutoff) %>% pull()

  expand_cts <- process_output %>%
    uncount(pt_ct)

  thrs_cutoffs <- expand_cts %>%
    mutate(user_thrs = ifelse(abs(num_days) <= user_cutoff, 1, 0)) %>%
    pivot_longer(cols = c('user_thrs')) %>%
    group_by(site, user_cutoff, total_pts, name, time_start) %>%
    summarise(n_pts_thrs = sum(value, na.rm = TRUE)) %>%
    mutate(prop_pts_thrs = round(n_pts_thrs / total_pts, 3)) %>% ungroup()

  #if(time_inc == 'year'){

    final <- thrs_cutoffs %>%
      #unite(facet_col, !!!syms(facet), sep = '\n') %>%
      rename('ycol' = n_pts_thrs,
             'denom' = total_pts)

    pp_qi <-  qic(data = final, x = time_start, y = ycol, chart = 'pp', #facet = ~facet_col,
                  title = paste0('Control Chart: Proportion of Patients Meeting User Threshold'),
                  ylab = 'Proportion', xlab = 'Time',
                  show.grid = TRUE, n = denom)

    op_dat <- pp_qi$data

    new_pp <- ggplot(op_dat,aes(x,y)) +
      geom_ribbon(aes(ymin = lcl,ymax = ucl), fill = "lightgray",alpha = 0.4) +
      geom_line(colour = squba_colors_standard[[12]], size = .5) +
      geom_line(aes(x,cl)) +
      geom_point(colour = squba_colors_standard[[6]] , fill = squba_colors_standard[[6]], size = 1) +
      geom_point(data = subset(op_dat, y >= ucl), color = squba_colors_standard[[3]], size = 2) +
      geom_point(data = subset(op_dat, y <= lcl), color = squba_colors_standard[[3]], size = 2) +
      #facet_wrap(~facet1, scales = 'free_y', ncol = 2) +
      ggtitle(label = paste0('Control Chart: Proportion of Patients Meeting \n', thrs, ' User Threshold')) +
      labs(x = 'Time',
           y = 'Proportion')+
      theme_minimal()

    new_pp[["metadata"]] <- tibble('pkg_backend' = 'plotly',
                                   'tooltip' = FALSE)

    return(new_pp)

}


#' *Multi-Site, Anomaly, Cross-Sectional*
#'
#' @param process_output output generated by the `pes_process` function
#' @param large_n a boolean indicating whether the large N visualization, intended for a high
#'                volume of sites, should be used; defaults to FALSE
#' @param large_n_sites a vector of site names that can optionally generate a filtered visualization
#'
#' @return a dot plot where the shape of the dot represents whether the point is
#'         anomalous, the color of the dot represents the proportion of patients
#'         for a given threshold window, and the size of the dot represents the mean proportion
#'         across all sites
#'
pes_ms_anom_cs <- function(process_output,
                           large_n = FALSE,
                           large_n_sites = NULL){

  check_n <- process_output %>%
    filter(anomaly_yn != 'no outlier in group')

  dat_to_plot <- process_output %>%
    mutate(label = case_when(threshold_cutoff == 'thirty_thrs' ~ '30 days',
                             threshold_cutoff == 'sixty_thrs' ~ '60 days',
                             threshold_cutoff == 'ninety_thrs' ~ '90 days',
                             threshold_cutoff == 'year_thrs' ~ '1 year',
                             threshold_cutoff == 'user_thrs' ~ paste0('User Threshold \n',
                                                                      user_cutoff, ' days'),
                             threshold_cutoff == 'pts_without_both' ~ 'Both Events Not Present'),
           nums = case_when(threshold_cutoff == 'thirty_thrs' ~ 30,
                            threshold_cutoff == 'sixty_thrs' ~ 60,
                            threshold_cutoff == 'ninety_thrs' ~ 90,
                            threshold_cutoff == 'year_thrs' ~ 365,
                            threshold_cutoff == 'user_thrs' ~ 99998,
                            threshold_cutoff == 'pts_without_both' ~ 99999),
           text = paste0('Site: ', site,
                         '\nProportion: ', prop_pts_thrs,
                         "\nMean proportion:",round(mean_val,2),
                         '\nSD: ', round(sd_val,2),
                         "\nMedian proportion: ",round(median_val,2),
                         "\nMAD: ", round(mad_val,2))) %>%
    mutate(anomaly_yn = ifelse(anomaly_yn == 'no outlier in group', 'not outlier', anomaly_yn)) %>%
    arrange(desc(nums)) %>%
    mutate(labs = factor(label, levels = unique(label)))

  if(!large_n){
    if(nrow(check_n) > 0){

      plt<-ggplot(dat_to_plot,
                  aes(x=site, y=labs, text=text, color=prop_pts_thrs))+
        geom_point_interactive(aes(size=mean_val,shape=anomaly_yn, tooltip = text))+
        geom_point_interactive(data = dat_to_plot %>% filter(anomaly_yn == 'not outlier'),
                               aes(size=mean_val,shape=anomaly_yn, tooltip = text), shape = 1, color = 'black')+
        scale_color_squba(palette = 'diverging', discrete = FALSE) +
        scale_shape_manual(values=c(19,8))+
        #scale_y_discrete(labels = function(x) str_wrap(x, width = text_wrapping_char)) +
        theme_minimal() +
        #theme(axis.text.x = element_text(angle=60, hjust = 1)) +
        labs(y = "Threshold Cutoff",
             x = '',
             size="",
             title=paste0('Anomalous Proportion Patients per \nThreshold Cutoff by Site'),
             subtitle = 'Dot size is the mean proportion per group') +
        guides(color = guide_colorbar(title = 'Proportion'),
               shape = guide_legend(title = 'Anomaly'),
               size = 'none')

      plt[["metadata"]] <- tibble('pkg_backend' = 'ggiraph',
                                  'tooltip' = TRUE)

      return(plt)

    }else{
      plt <- ggplot(dat_to_plot, aes(x = site, y = labs, fill = prop_pts_thrs,
                                     tooltip = text)) +
        geom_tile_interactive() +
        theme_minimal() +
        scale_fill_squba(discrete = FALSE, palette = 'diverging') +
        labs(y = 'Threshold Cutoff',
             x = 'Site',
             fill = 'Proportion')

      # Test Site Score using SD Computation
      test_site_score <- process_output %>%
        mutate(dist_mean = (prop_pts_thrs - mean_val)^2) %>%
        group_by(site) %>%
        summarise(n_grp = n(),
                  dist_mean_sum = sum(dist_mean),
                  overall_sd = sqrt(dist_mean_sum / n_grp)) %>%
        mutate(tooltip = paste0('Site: ', site,
                                '\nStandard Deviation: ', round(overall_sd, 3)))

      ylim_max <- test_site_score %>% filter(overall_sd == max(overall_sd)) %>% pull(overall_sd) + 1
      ylim_min <- test_site_score %>% filter(overall_sd == min(overall_sd)) %>% pull(overall_sd) - 1

      g2 <- ggplot(test_site_score, aes(y = overall_sd, x = site, color = site,
                                        tooltip = tooltip)) +
        geom_point_interactive(show.legend = FALSE) +
        theme_minimal() +
        scale_color_squba() +
        geom_hline(yintercept = 0, linetype = 'solid') +
        labs(title = 'Average Standard Deviation per Site',
             y = 'Average Standard Deviation',
             x = 'Site')

      plt[["metadata"]] <- tibble('pkg_backend' = 'ggiraph',
                                  'tooltip' = TRUE)
      g2[["metadata"]] <- tibble('pkg_backend' = 'ggiraph',
                                 'tooltip' = TRUE)

      opt <- list(plt,
                  g2)

      return(opt)
    }
  }else{

    process_output <- process_output %>%
      mutate(label = case_when(threshold_cutoff == 'thirty_thrs' ~ '30 days',
                               threshold_cutoff == 'sixty_thrs' ~ '60 days',
                               threshold_cutoff == 'ninety_thrs' ~ '90 days',
                               threshold_cutoff == 'year_thrs' ~ '1 year',
                               threshold_cutoff == 'user_thrs' ~ paste0('User Threshold \n',
                                                                        user_cutoff, ' days'),
                               threshold_cutoff == 'pts_without_both' ~ 'Both Events Not Present'),
             nums = case_when(threshold_cutoff == 'thirty_thrs' ~ 30,
                              threshold_cutoff == 'sixty_thrs' ~ 60,
                              threshold_cutoff == 'ninety_thrs' ~ 90,
                              threshold_cutoff == 'year_thrs' ~ 365,
                              threshold_cutoff == 'user_thrs' ~ 99998,
                              threshold_cutoff == 'pts_without_both' ~ 99999)) %>%
      arrange(nums)

    suppressWarnings(
      far_site <- process_output %>%
        # filter(anomaly_yn != 'no outlier in group') %>%
        mutate(zscr = (prop_pts_thrs - mean_val) / sd_val,
               zscr = ifelse(is.nan(zscr), NA, zscr),
               zscr = abs(zscr)) %>%
        group_by(label) %>%
        filter(zscr == max(zscr, na.rm = TRUE)) %>%
        summarise(farthest_site = site,
                  nvar = n())

    )

    if(any(far_site$nvar > 1)){
      far_site <- far_site %>%
        summarise_all(toString) %>% select(-nvar)
    }else{
      far_site <- far_site %>% select(-nvar)
    }

    suppressWarnings(
      close_site <- process_output %>%
        # filter(anomaly_yn != 'no outlier in group') %>%
        mutate(zscr = (prop_pts_thrs - mean_val) / sd_val,
               zscr = ifelse(is.nan(zscr), NA, zscr),
               zscr = abs(zscr)) %>%
        group_by(label) %>%
        filter(zscr == min(zscr, na.rm = TRUE)) %>%
        summarise(closest_site = site,
                  nvar = n())
    )

    if(any(close_site$nvar > 1)){
      close_site <- close_site %>%
        summarise_all(toString) %>% select(-nvar)
    }else{
      close_site <- close_site %>% select(-nvar)
    }

    nsite_anom <- process_output %>%
      group_by(label, anomaly_yn) %>%
      summarise(site_w_anom = n_distinct(site)) %>%
      filter(anomaly_yn == 'outlier') %>%
      ungroup() %>%
      select(-anomaly_yn)

    sitesanoms <- process_output %>%
      filter(anomaly_yn == 'outlier') %>%
      group_by(label) %>%
      summarise(site_anoms = toString(site)) %>%
      select(label, site_anoms)

    tbl <- process_output %>%
      group_by(label) %>%
      mutate(iqr_val = stats::IQR(prop_pts_thrs)) %>%
      ungroup() %>%
      distinct(label, mean_val, sd_val, median_val, iqr_val) %>%
      left_join(nsite_anom) %>%
      left_join(sitesanoms) %>%
      left_join(far_site) %>%
      left_join(close_site) %>%
      mutate(delim = sub("^([^,]+,){5}([^,]+).*", "\\2", site_anoms),
             site_anoms = ifelse(site_w_anom > 5,
                                 stringr::str_replace(site_anoms, paste0(",", delim, '(.*)'), ' . . .'),
                                 site_anoms)) %>%
      select(-delim) %>%
      gt::gt() %>%
      tab_header('Large N Anomaly Detection Summary Table') %>%
      cols_label(label = 'Threshold Cutoff',
                 site_anoms = 'Site(s) with Anomaly',
                 mean_val = 'Mean',
                 sd_val = 'Standard Deviation',
                 median_val = 'Median',
                 iqr_val = 'IQR',
                 site_w_anom = 'No. Sites w/ Anomaly',
                 farthest_site = 'Site(s) Farthest from Mean',
                 closest_site = 'Site(s) Closest to Mean') %>%
      sub_missing(missing_text = 0,
                  columns = site_w_anom) %>%
      sub_missing(missing_text = '--',
                  columns = c(farthest_site, closest_site, site_anoms)) %>%
      fmt_number(columns = c(mean_val, median_val, sd_val, iqr_val),
                 decimals = 3) %>%
      opt_stylize(style = 2)

    if(!is.null(large_n_sites)){
      plt<-ggplot(dat_to_plot %>% filter(site %in% large_n_sites),
                  aes(x=site, y=labs, text=text, color=prop_pts_thrs))+
        geom_point_interactive(aes(size=mean_val,shape=anomaly_yn, tooltip = text))+
        geom_point_interactive(data = dat_to_plot %>% filter(anomaly_yn == 'not outlier',
                                                             site %in% large_n_sites),
                               aes(size=mean_val,shape=anomaly_yn, tooltip = text), shape = 1, color = 'black')+
        scale_color_squba(palette = 'diverging', discrete = FALSE) +
        scale_shape_manual(values=c(19,8))+
        scale_y_discrete(labels = label_wrap_gen()) +
        theme_minimal() +
        labs(y = "Variable",
             size="",
             title=paste0('Anomalous Proportion Patients per \nThreshold Cutoff by Site'),
             subtitle = 'Dot size is the mean proportion per group') +
        guides(color = guide_colorbar(title = 'Proportion'),
               shape = guide_legend(title = 'Anomaly'),
               size = 'none')

      plt[['metadata']] <- tibble('pkg_backend' = 'ggiraph',
                                  'tooltip' = TRUE)

      opt <- list(plt,
                  tbl)

      return(opt)
    }else{
      return(tbl)
    }
  }

}


#' *Multi-Site, Anomaly, Longitudinal*
#'
#' @param process_output output generated by the `pes_process` function
#' @param large_n a boolean indicating whether the large N visualization, intended for a high
#'                volume of sites, should be used; defaults to FALSE
#' @param large_n_sites a vector of site names that can optionally generate a filtered visualization
#'
#' @return three graphs:
#'    1) line graph that shows the smoothed proportion of patients who meet the user provided threshold
#'    of time between events across time with the Euclidean distance associated with each line
#'    2) line graph that shows the raw proportion of patients who meet the user provided threshold
#'    of time between events across time with the Euclidean distance associated with each line
#'    3) a bar graph with the Euclidean distance value for each site, with the average
#'    proportion as the fill
#'
pes_ms_anom_la <- function(process_output,
                           large_n = FALSE,
                           large_n_sites = NULL){

  thrs <- process_output %>% distinct(user_cutoff) %>% pull()

  allsites <-
    process_output %>%
    select(time_start,mean_allsiteprop) %>% distinct() %>%
    rename(prop_col=mean_allsiteprop) %>%
    mutate(site='all site average') %>%
    mutate(text_smooth=paste0("Site: ", site,
                              "\n","Proportion: ",prop_col),
           text_raw=paste0("Site: ", site,
                           "\n","Proportion: ",prop_col))

  iqr_dat <- process_output %>%
    select(time_start,prop_pts_thrs) %>% distinct() %>%
    group_by(time_start) %>%
    summarise(q1 = stats::quantile(prop_pts_thrs, 0.25),
              q3 = stats::quantile(prop_pts_thrs, 0.75))

  dat_to_plot <-
    process_output %>%
    rename(prop_col=prop_pts_thrs) %>%
    mutate(text_smooth=paste0("Site: ", site,
                              "\n","Euclidean Distance from All-Site Mean: ",dist_eucl_mean),
           text_raw=paste0("Site: ", site,
                           "\n","Site Proportion: ",prop_col,
                           "\n","Site Smoothed Proportion: ",site_loess,
                           "\n","Euclidean Distance from All-Site Mean: ",dist_eucl_mean))

  if(!large_n){
    p <- dat_to_plot %>%
      ggplot(aes(y = prop_col, x = time_start, color = site, group = site, text = text_smooth)) +
      geom_line(data=allsites, linewidth=1.1) +
      geom_smooth(se=TRUE,alpha=0.1,linewidth=0.5, formula = y ~ x) +
      theme_minimal() +
      scale_color_squba() +
      labs(y = 'Proportion (Loess)',
           x = 'Time',
           title = paste0('Smoothed Proportion of Patients Meeting \n', thrs, ' Day User Threshold'))

    q <- dat_to_plot %>%
      ggplot(aes(y = prop_col, x = time_start, color = site,
                 group=site, text=text_raw)) +
      geom_line(data=allsites,linewidth=1.1) +
      geom_line(linewidth=0.2) +
      theme_minimal() +
      scale_color_squba() +
      labs(x = 'Time',
           y = 'Proportion',
           title = paste0('Raw Proportion of Patients Meeting \n', thrs, ' Day User Threshold'))

    t <- dat_to_plot %>%
      distinct(site, dist_eucl_mean, site_loess) %>%
      group_by(site, dist_eucl_mean) %>%
      summarise(mean_site_loess = mean(site_loess)) %>%
      mutate(tooltip = paste0('Site: ', site,
                              '\nEuclidean Distance: ', dist_eucl_mean,
                              '\nAverage Loess Proportion: ', mean_site_loess)) %>%
      ggplot(aes(x = site, y = dist_eucl_mean, fill = mean_site_loess, tooltip = tooltip)) +
      geom_segment(aes(x = site, xend = site, y = 0, yend = dist_eucl_mean), color = 'navy') +
      geom_point_interactive(aes(fill = mean_site_loess), shape = 21, size = 4) +
      coord_radial(r.axis.inside = FALSE, rotate.angle = TRUE) +
      guides(theta = guide_axis_theta(angle = 0)) +
      theme_minimal() +
      scale_fill_squba(palette = 'diverging', discrete = FALSE) +
      labs(fill = 'Avg. Proportion \n(Loess)',
           y ='Euclidean Distance',
           x = '',
           title = paste0('Euclidean Distance for \n', thrs, ' Day User Threshold'))

    p[['metadata']] <- tibble('pkg_backend' = 'plotly',
                              'tooltip' = TRUE)

    q[['metadata']] <- tibble('pkg_backend' = 'plotly',
                              'tooltip' = TRUE)

    t[['metadata']] <- tibble('pkg_backend' = 'ggiraph',
                              'tooltip' = TRUE)

    output <- list(p,q,t)
  }else{
    q <- ggplot(allsites, aes(x = time_start)) +
      geom_ribbon(data = iqr_dat, aes(ymin = q1, ymax = q3), alpha = 0.2) +
      geom_line(aes(y = prop_col, color = site, group = site), linewidth=1.1) +
      geom_point_interactive(aes(y = prop_col, color = site, group = site, tooltip=text_raw)) +
      theme_minimal() +
      #theme(axis.text.x = element_text(angle = 30, vjust = 1, hjust=1)) +
      scale_color_squba() +
      labs(x = 'Time',
           y = 'Proportion',
           title = paste0('Proportion of Patients Meeting \n', thrs, ' Day User Threshold'),
           subtitle = 'Ribbon boundaries are IQR')

    if(is.null(large_n_sites)){

      t <- dat_to_plot %>%
        distinct(user_cutoff, dist_eucl_mean) %>%
        ggplot(aes(x = dist_eucl_mean, y = user_cutoff)) +
        geom_boxplot() +
        geom_point_interactive(color = 'gray',
                               alpha = 0.75, aes(tooltip = dist_eucl_mean)) +
        theme_minimal() +
        theme(axis.text.y = element_blank(),
              legend.title = element_blank()) +
        scale_fill_squba(palette = 'diverging', discrete = FALSE) +
        labs(x ='Euclidean Distance',
             y = '',
             title = paste0('Distribution of Euclidean Distances'))

    }else{
      q <- q + geom_line(data = dat_to_plot %>% filter(site %in% large_n_sites),
                         aes(y = prop_col, color = site, group = site),
                         linewidth=0.2) +
        geom_point_interactive(data = dat_to_plot %>% filter(site %in% large_n_sites),
                               aes(y = prop_col, color = site, group = site, tooltip=text_raw))

      t <- dat_to_plot %>%
        distinct(user_cutoff,dist_eucl_mean) %>%
        ggplot(aes(x = dist_eucl_mean, y = user_cutoff)) +
        geom_boxplot() +
        geom_point_interactive(data = dat_to_plot %>% filter(site %in% large_n_sites),
                               aes(color = site, tooltip = dist_eucl_mean)) +
        theme_minimal() +
        theme(axis.text.y = element_blank(),
              legend.title = element_blank()) +
        scale_fill_squba(palette = 'diverging', discrete = FALSE) +
        scale_color_squba() +
        labs(x ='Euclidean Distance',
             y = '',
             title = paste0('Distribution of Euclidean Distances'))
    }

    q[['metadata']] <- tibble('pkg_backend' = 'ggiraph',
                              'tooltip' = TRUE)
    t[['metadata']] <- tibble('pkg_backend' = 'ggiraph',
                              'tooltip' = TRUE)

    output <- q + t + plot_layout(ncol = 1, heights = c(5, 1))
  }

  return(output)


}

