
#'
#' @import ggplot2
#' @import ggiraph
#' @importFrom qicharts2 qic
#' @importFrom tidyr uncount
#' @importFrom tidyr pivot_longer
#' @importFrom stats median
#' @importFrom patchwork wrap_plots
#' @importFrom patchwork plot_layout
#' @importFrom graphics text
NULL

#' *Single Site, Exploratory, No Time*
#'
#' @param process_output output generated by the `pes_process` function
#'
#' @return a patchworked object with a histogram showing the distribution of days between events
#'         with a line representing the median number of days and a bar graph representing the
#'         proportion of patients excluded from the histogram because they did not have evidence
#'         of event b
#' @return a bar graph representing the proportion of patients that meet a set of
#'         thresholds: 30 days, 60 days, 90 days, one year, and the user provided
#'         threshold value
#'
pes_ss_exp_nt <- function(process_output){


  expand_cts <- process_output %>%
    uncount(pt_ct)

  median_days <- median(expand_cts$num_days, na.rm = TRUE)

  hstgrm <- ggplot(expand_cts, aes(x = num_days, fill = num_days, group = num_days)) +
    geom_histogram() +
    geom_vline(xintercept = median_days,
               linetype = 'dotted') +
    theme_minimal() +
    theme(legend.position = 'none') +
    scale_fill_ssdqa(discrete = FALSE) +
    labs(x = 'Days Between Events',
         title = 'Distribution of Time Between Events')

  ## Missing Event Bar Graph
  missing_events <- process_output %>%
    mutate(prop_miss = pts_without_both / total_pts,
           xlab = '')

  miss_grph <- missing_events %>%
    ggplot(aes(y = prop_miss, x = xlab, fill = xlab)) +
    geom_col(show.legend = FALSE) +
    geom_label(aes(label = round(prop_miss, 3)), fill = 'white') +
    scale_fill_manual(values = ssdqa_colors_standard[[2]]) +
    theme_minimal() +
    ylim(0,1) +
    labs(x = '',
         y = 'Proportion Patients without Both Events')

  thrs_cutoffs <- expand_cts %>%
    mutate(user_thrs = ifelse(abs(num_days) <= user_cutoff, 1, 0),
           thirty_thrs = ifelse(abs(num_days) <= 30, 1, 0),
           sixty_thrs = ifelse(abs(num_days) <= 60, 1, 0),
           ninety_thrs = ifelse(abs(num_days) <= 90, 1, 0),
           year_thrs = ifelse(abs(num_days) <= 365, 1, 0)) %>%
    pivot_longer(cols = c('user_thrs', 'thirty_thrs', 'sixty_thrs',
                          'ninety_thrs', 'year_thrs')) %>%
    group_by(site, user_cutoff, total_pts, name) %>%
    summarise(n_pts_thrs = sum(value, na.rm = TRUE)) %>%
    mutate(prop_pts_thrs = round(n_pts_thrs / total_pts, 3))

  bgrph <- thrs_cutoffs %>%
    mutate(label = case_when(name == 'thirty_thrs' ~ '30 days',
                             name == 'sixty_thrs' ~ '60 days',
                             name == 'ninety_thrs' ~ '90 days',
                             name == 'year_thrs' ~ '1 year',
                             name == 'user_thrs' ~ paste0('User Threshold \n',
                                                          user_cutoff, ' days')),
           nums = case_when(name == 'thirty_thrs' ~ 1,
                            name == 'sixty_thrs' ~ 2,
                            name == 'ninety_thrs' ~ 3,
                            name == 'year_thrs' ~ 4,
                            name == 'user_thrs' ~ 5)) %>%
    arrange(nums) %>%
    mutate(lb = factor(label, levels = unique(label))) %>%
    ggplot(aes(x = lb, y = prop_pts_thrs, fill = lb)) +
    geom_col() +
    theme_minimal() +
    theme(legend.position = 'none') +
    scale_fill_ssdqa() +
    labs(x = 'Threshold',
         y = 'Proportion Patients',
         title = 'Proportion of Patients where Events \nOccur within Threshold Window')

  bgrph[["metadata"]] <- tibble('pkg_backend' = 'plotly',
                                'tooltip' = FALSE)

  plt_grp <- patchwork::wrap_plots(hstgrm, miss_grph) +
    patchwork::plot_layout(widths = c(8, 3))

  otpt <- list(plt_grp,
               bgrph)

  return(otpt)

}


#' *Multi-Site, Exploratory, No Time*
#'
#' @param process_output output generated by the `pes_process` function
#'
#' @return a bar graph representing the proportion of patients at each site
#'         that meet a set of thresholds: 30 days, 60 days, 90 days, one year,
#'         and the user provided threshold value
#'
#'         dotted line represents the all site median
#'
pes_ms_exp_nt <- function(process_output){


  expand_cts <- process_output %>%
    uncount(pt_ct)

  without_both_thrs <- process_output %>%
    select(site, user_cutoff, total_pts, pts_without_both) %>%
    pivot_longer(cols = 'pts_without_both',
                 names_to = 'name',
                 values_to = 'n_pts_thrs') %>%
    mutate(prop_pts_thrs = round(n_pts_thrs / total_pts, 3)) %>% distinct()

  thrs_cutoffs <- expand_cts %>%
    mutate(user_thrs = ifelse(abs(num_days) <= user_cutoff, 1, 0),
           thirty_thrs = ifelse(abs(num_days) <= 30, 1, 0),
           sixty_thrs = ifelse(abs(num_days) <= 60, 1, 0),
           ninety_thrs = ifelse(abs(num_days) <= 90, 1, 0),
           year_thrs = ifelse(abs(num_days) <= 365, 1, 0)) %>%
    pivot_longer(cols = c('user_thrs', 'thirty_thrs', 'sixty_thrs',
                          'ninety_thrs', 'year_thrs')) %>%
    group_by(site, user_cutoff, total_pts, name) %>%
    summarise(n_pts_thrs = sum(value, na.rm = TRUE)) %>%
    mutate(prop_pts_thrs = round(n_pts_thrs / total_pts, 3)) %>%
    union(without_both_thrs) %>%
    group_by(name) %>%
    mutate(median_prop = median(prop_pts_thrs))

  bgrph <- thrs_cutoffs %>%
    mutate(label = case_when(name == 'thirty_thrs' ~ '30 days',
                             name == 'sixty_thrs' ~ '60 days',
                             name == 'ninety_thrs' ~ '90 days',
                             name == 'year_thrs' ~ '1 year',
                             name == 'user_thrs' ~ paste0('User Threshold \n',
                                                          user_cutoff, ' days'),
                             name == 'pts_without_both' ~ 'Both Events \nNot Present'),
           nums = case_when(name == 'thirty_thrs' ~ 1,
                            name == 'sixty_thrs' ~ 2,
                            name == 'ninety_thrs' ~ 3,
                            name == 'year_thrs' ~ 4,
                            name == 'user_thrs' ~ 5,
                            name == 'pts_without_both' ~ 6)) %>%
    arrange(nums) %>%
    # mutate(lb = factor(label, levels = unique(label))) %>%
    ggplot(aes(y = site, x = prop_pts_thrs, fill = label)) +
    geom_col() +
    facet_wrap(~factor(nums, labels = unique(label))) +
    geom_vline(mapping = aes(xintercept = median_prop),
               linetype = 'dotted') +
    theme_minimal() +
    theme(legend.position = 'none') +
    scale_fill_ssdqa() +
    labs(x = 'Site',
         y = 'Proportion Patients',
         title = 'Proportion of Patients where Events \nOccur within Threshold Window')

  bgrph[["metadata"]] <- tibble('pkg_backend' = 'plotly',
                                'tooltip' = FALSE)

  return(bgrph)

}

#' *Single Site, Exploratory, Across Time*
#'
#' @param process_output output generated by the `pes_process` function
#'
#' @return a line graph displaying the proportion of patients meeting the user provided
#'         threshold of time between events over time
#'
pes_ss_exp_at <- function(process_output){

  expand_cts <- process_output %>%
    uncount(pt_ct)

  time_period <- process_output %>% select(time_increment) %>% distinct() %>% pull()
  thrs <- process_output %>% select(user_cutoff) %>% distinct() %>% pull()

  thrs_cutoffs <- expand_cts %>%
    mutate(user_thrs = ifelse(abs(num_days) <= user_cutoff, 1, 0)) %>%
    pivot_longer(cols = c('user_thrs')) %>%
    group_by(site, user_cutoff, total_pts, name, time_start) %>%
    summarise(n_pts_thrs = sum(value, na.rm = TRUE)) %>%
    mutate(prop_pts_thrs = round(n_pts_thrs / total_pts, 3),
           text = paste0('Proportion: ', prop_pts_thrs,
                         '\nTotal Patients: ', total_pts)) %>% ungroup()


  lgrph <- ggplot(thrs_cutoffs,
                 aes(x = time_start, y = prop_pts_thrs, color = site)) +
    geom_line() +
    theme_minimal() +
    scale_color_ssdqa() +
    labs(y = 'Proportion',
         x = 'Time',
         color = 'Site',
         title = paste0('Proportion of Patients Meeting \n', thrs, ' Day User Threshold'),
         subtitle = paste0('When Event A occurs within each ', time_period))

  lgrph[["metadata"]] <- tibble('pkg_backend' = 'plotly',
                                'tooltip' = FALSE)

  return(lgrph)

}

#' *Multi-Site, Exploratory, Across Time*
#'
#' @param process_output output generated by the `pes_process` function
#'
#' @return a line graph displaying the proportion of patients meeting the user provided
#'         threshold of time between events over time; each line represents an individual site,
#'         with an additional line representing the all site median
#'
pes_ms_exp_at <- function(process_output){

  expand_cts <- process_output %>%
    uncount(pt_ct)

  time_period <- process_output %>% select(time_increment) %>% distinct() %>% pull()
  thrs <- process_output %>% select(user_cutoff) %>% distinct() %>% pull()

  thrs_cutoffs <- expand_cts %>%
    mutate(user_thrs = ifelse(abs(num_days) <= user_cutoff, 1, 0)) %>%
    pivot_longer(cols = c('user_thrs')) %>%
    group_by(site, user_cutoff, total_pts, name, time_start) %>%
    summarise(n_pts_thrs = sum(value, na.rm = TRUE)) %>%
    mutate(prop_pts_thrs = round(n_pts_thrs / total_pts, 3),
           text = paste0('Proportion: ', prop_pts_thrs,
                         '\nTotal Patients: ', total_pts)) %>% ungroup()

  allsite_median <- thrs_cutoffs %>%
    group_by(name, time_start) %>%
    mutate(prop_pts_thrs = median(prop_pts_thrs),
           site = 'All Site Median',
           text = paste0('All Site Median: ', prop_pts_thrs)) %>%
    ungroup() %>%
    select(site, time_start, prop_pts_thrs, text) %>% distinct()


  grph <- ggplot(thrs_cutoffs,
                 aes(x = time_start, y = prop_pts_thrs, color = site)) +
    geom_line() +
    geom_line(data = filter(allsite_median, site == "All Site Median"), size = 1.5) +
    theme_minimal() +
    scale_color_ssdqa() +
    labs(y = 'Proportion',
         x = 'Time',
         color = 'Site',
         title = paste0('Proportion of Patients Meeting \n', thrs, ' Day User Threshold'),
         subtitle = paste0('When Event A occurs within each ', time_period))

  grph[["metadata"]] <- tibble('pkg_backend' = 'plotly',
                               'tooltip' = FALSE)

  return(grph)

}


#' *Single Site, Anomaly, Across Time*
#'
#' @param process_output output generated by the `pes_process` function
#'
#' @return a control chart highlighting anomalies in the proportion of patients
#'         meeting the user defined threshold of time between events
#'
pes_ss_anom_at <- function(process_output){

  thrs <- process_output %>% distinct(user_cutoff) %>% pull()

  expand_cts <- process_output %>%
    uncount(pt_ct)

  thrs_cutoffs <- expand_cts %>%
    mutate(user_thrs = ifelse(abs(num_days) <= user_cutoff, 1, 0)) %>%
    pivot_longer(cols = c('user_thrs')) %>%
    group_by(site, user_cutoff, total_pts, name, time_start) %>%
    summarise(n_pts_thrs = sum(value, na.rm = TRUE)) %>%
    mutate(prop_pts_thrs = round(n_pts_thrs / total_pts, 3)) %>% ungroup()

  #if(time_inc == 'year'){

    final <- thrs_cutoffs %>%
      #unite(facet_col, !!!syms(facet), sep = '\n') %>%
      rename('ycol' = n_pts_thrs,
             'denom' = total_pts)

    pp_qi <-  qic(data = final, x = time_start, y = ycol, chart = 'pp', #facet = ~facet_col,
                  title = paste0('Control Chart: Proportion of Patients Meeting User Threshold'),
                  ylab = 'Proportion', xlab = 'Time',
                  show.grid = TRUE, n = denom)

    op_dat <- pp_qi$data

    new_pp <- ggplot(op_dat,aes(x,y)) +
      geom_ribbon(aes(ymin = lcl,ymax = ucl), fill = "lightgray",alpha = 0.4) +
      geom_line(colour = ssdqa_colors_standard[[12]], size = .5) +
      geom_line(aes(x,cl)) +
      geom_point(colour = ssdqa_colors_standard[[6]] , fill = ssdqa_colors_standard[[6]], size = 1) +
      geom_point(data = subset(op_dat, y >= ucl), color = ssdqa_colors_standard[[3]], size = 2) +
      geom_point(data = subset(op_dat, y <= lcl), color = ssdqa_colors_standard[[3]], size = 2) +
      #facet_wrap(~facet1, scales = 'free_y', ncol = 2) +
      ggtitle(label = paste0('Control Chart: Proportion of Patients Meeting \n', thrs, ' User Threshold')) +
      labs(x = 'Time',
           y = 'Proportion')+
      theme_minimal()

    new_pp[["metadata"]] <- tibble('pkg_backend' = 'plotly',
                                   'tooltip' = FALSE)

    return(new_pp)

}


#' *Multi-Site, Anomaly, No Time*
#'
#' @param process_output output generated by the `pes_process` function
#'
#' @return a dot plot where the shape of the dot represents whether the point is
#'         anomalous, the color of the dot represents the proportion of patients
#'         for a given threshold window, and the size of the dot represents the mean proportion
#'         across all sites
#'
pes_ms_anom_nt <- function(process_output){


  dat_to_plot <- process_output %>%
    mutate(label = case_when(threshold_cutoff == 'thirty_thrs' ~ '30 days',
                             threshold_cutoff == 'sixty_thrs' ~ '60 days',
                             threshold_cutoff == 'ninety_thrs' ~ '90 days',
                             threshold_cutoff == 'year_thrs' ~ '1 year',
                             threshold_cutoff == 'user_thrs' ~ paste0('User Threshold \n',
                                                               user_cutoff, ' days'),
                             threshold_cutoff == 'pts_without_both' ~ 'Both Events Not Present'),
           nums = case_when(threshold_cutoff == 'thirty_thrs' ~ 30,
                            threshold_cutoff == 'sixty_thrs' ~ 60,
                            threshold_cutoff == 'ninety_thrs' ~ 90,
                            threshold_cutoff == 'year_thrs' ~ 365,
                            threshold_cutoff == 'user_thrs' ~ 99998,
                            threshold_cutoff == 'pts_without_both' ~ 99999),
           text = paste0('Site: ', site,
                         '\nProportion: ', prop_pts_thrs,
                         "\nMean proportion:",round(mean_val,2),
                         '\nSD: ', round(sd_val,2),
                         "\nMedian proportion: ",round(median_val,2),
                         "\nMAD: ", round(mad_val,2))) %>%
    mutate(anomaly_yn = ifelse(anomaly_yn == 'no outlier in group', 'not outlier', anomaly_yn)) %>%
    arrange(desc(nums)) %>%
    mutate(labs = factor(label, levels = unique(label)))

  plt<-ggplot(dat_to_plot,
              aes(x=site, y=labs, text=text, color=prop_pts_thrs))+
    geom_point_interactive(aes(size=mean_val,shape=anomaly_yn, tooltip = text))+
    geom_point_interactive(data = dat_to_plot %>% filter(anomaly_yn == 'not outlier'),
                           aes(size=mean_val,shape=anomaly_yn, tooltip = text), shape = 1, color = 'black')+
    scale_color_ssdqa(palette = 'diverging', discrete = FALSE) +
    scale_shape_manual(values=c(19,8))+
    #scale_y_discrete(labels = function(x) str_wrap(x, width = text_wrapping_char)) +
    theme_minimal() +
    #theme(axis.text.x = element_text(angle=60, hjust = 1)) +
    labs(y = "Threshold Cutoff",
         x = '',
         size="",
         title=paste0('Anomalous Proportion Patients per \nThreshold Cutoff by Site'),
         subtitle = 'Dot size is the mean proportion per group') +
    guides(color = guide_colorbar(title = 'Proportion'),
           shape = guide_legend(title = 'Anomaly'),
           size = 'none')

  plt[["metadata"]] <- tibble('pkg_backend' = 'ggiraph',
                              'tooltip' = TRUE)

  return(plt)

}


#' *Multi-Site, Anomaly, Across Time*
#'
#' @param process_output output generated by the `pes_process` function
#'
#' @return three graphs:
#'    1) line graph that shows the smoothed proportion of patients who meet the user provided threshold
#'    of time between events across time with the Euclidean distance associated with each line
#'    2) line graph that shows the raw proportion of patients who meet the user provided threshold
#'    of time between events across time with the Euclidean distance associated with each line
#'    3) a bar graph with the Euclidean distance value for each site, with the average
#'    proportion as the fill
#'
pes_ms_anom_at <- function(process_output){

  thrs <- process_output %>% distinct(user_cutoff) %>% pull()

  allsites <-
    process_output %>%
    select(time_start,mean_allsiteprop) %>% distinct() %>%
    rename(prop_col=mean_allsiteprop) %>%
    mutate(site='all site average') %>%
    mutate(text_smooth=paste0("Site: ", site,
                              "\n","Proportion: ",prop_col),
           text_raw=paste0("Site: ", site,
                           "\n","Proportion: ",prop_col))

  dat_to_plot <-
    process_output %>%
    rename(prop_col=prop_pts_thrs) %>%
    mutate(text_smooth=paste0("Site: ", site,
                              "\n","Euclidean Distance from All-Site Mean: ",dist_eucl_mean),
           text_raw=paste0("Site: ", site,
                           "\n","Site Proportion: ",prop_col,
                           "\n","Site Smoothed Proportion: ",site_loess,
                           "\n","Euclidean Distance from All-Site Mean: ",dist_eucl_mean))

  p <- dat_to_plot %>%
    ggplot(aes(y = prop_col, x = time_start, color = site, group = site, text = text_smooth)) +
    geom_line(data=allsites, linewidth=1.1) +
    geom_smooth(se=TRUE,alpha=0.1,linewidth=0.5, formula = y ~ x) +
    theme_minimal() +
    #theme(axis.text.x = element_text(angle = 30, vjust = 1, hjust=1)) +
    scale_color_ssdqa() +
    labs(y = 'Proportion (Loess)',
         x = 'Time',
         title = paste0('Smoothed Proportion of Patients Meeting \n', thrs, ' Day User Threshold'))

  q <- dat_to_plot %>%
    ggplot(aes(y = prop_col, x = time_start, color = site,
               group=site, text=text_raw)) +
    geom_line(data=allsites,linewidth=1.1) +
    geom_line(linewidth=0.2) +
    theme_minimal() +
    #theme(axis.text.x = element_text(angle = 30, vjust = 1, hjust=1)) +
    scale_color_ssdqa() +
    labs(x = 'Time',
         y = 'Proportion',
         title = paste0('Raw Proportion of Patients Meeting \n', thrs, ' Day User Threshold'))

  t <- dat_to_plot %>%
    distinct(site, dist_eucl_mean, site_loess) %>%
    group_by(site, dist_eucl_mean) %>%
    summarise(mean_site_loess = mean(site_loess)) %>%
    mutate(tooltip = paste0('Site: ', site,
                            '\nEuclidean Distance: ', dist_eucl_mean,
                            '\nAverage Loess Proportion: ', mean_site_loess)) %>%
    ggplot(aes(x = site, y = dist_eucl_mean, fill = mean_site_loess, tooltip = tooltip)) +
    geom_col_interactive() +
    # geom_text(aes(label = dist_eucl_mean), vjust = 2, size = 3,
    #           show.legend = FALSE) +
    coord_radial(r.axis.inside = FALSE, rotate.angle = TRUE) +
    guides(theta = guide_axis_theta(angle = 0)) +
    theme_minimal() +
    scale_fill_ssdqa(palette = 'diverging', discrete = FALSE) +
    # theme(legend.position = 'bottom',
    #       legend.text = element_text(angle = 45, vjust = 0.9, hjust = 1),
    #       axis.text.x = element_text(face = 'bold')) +
    labs(fill = 'Avg. Proportion \n(Loess)',
         y ='Euclidean Distance',
         x = '',
         title = paste0('Euclidean Distance for \n', thrs, ' Day User Threshold'))

  p[['metadata']] <- tibble('pkg_backend' = 'plotly',
                            'tooltip' = TRUE)

  q[['metadata']] <- tibble('pkg_backend' = 'plotly',
                            'tooltip' = TRUE)

  t[['metadata']] <- tibble('pkg_backend' = 'ggiraph',
                            'tooltip' = TRUE)

  output <- list(p,
                 q,
                 t)

  return(output)


}
