
#' Patient Event Sequencing -- Output Generation
#'
#' Using the tabular output generated by `pes_process`, this function will build a graph to
#' visualize the results. Each function configuration will output a bespoke ggplot. Theming can
#' be adjusted by the user after the graph has been output using `+ theme()`. Most graphs can
#' also be made interactive using `make_interactive_squba()`
#'
#' @param process_output the output of the `pes_process` function
#' @param output_function the name of the output function that should be used provided in the `parameter_summary` csv
#'                        file that is output to the provided results folder after running the `pes_process` function
#'
#' @return a graph or series of graphs visualizing the results from pes_process; see individual
#'         function documentation for more detail.
#'
#' @example inst/example-pes_process_output.R
#'
#' @export
#'
pes_output <- function(process_output,
                       output_function){


  if(output_function == 'pes_ss_exp_cs'){

    pes_output <- pes_ss_exp_cs(process_output = process_output)

  }else if(output_function == 'pes_ss_anom_cs'){

    cli_alert_danger('There is no available Single Site, Anomaly Detection, Cross-Sectional
                     output for this module. Please choose another output function.')

  }else if(output_function == 'pes_ms_exp_cs'){

    pes_output <- pes_ms_exp_cs(process_output = process_output)

  }else if(output_function == 'pes_ms_anom_cs'){

    pes_output <- pes_ms_anom_cs(process_output = process_output)

  }else if(output_function == 'pes_ss_exp_la'){

    pes_output <- pes_ss_exp_la(process_output = process_output)

  }else if(output_function == 'pes_ss_anom_la'){

    pes_output <- pes_ss_anom_la(process_output = process_output)

  }else if(output_function == 'pes_ms_exp_la'){

    pes_output <- pes_ms_exp_la(process_output = process_output)

  }else if(output_function == 'pes_ms_anom_la'){

    pes_output <- pes_ms_anom_la(process_output = process_output)

  }else{cli::cli_abort('Please enter a valid output_function for this check type.')}

  return(pes_output)
}
